### ISSUE TITLE
Support searching online by default

### ISSUE THREAD

**Issue by dcaixinha** [vdesabou/alfred-spotify-mini-player#125]
Would it be possible to add an option in Settings to search everywhere (`Your Music` and `Online`)? It'd be great not having to press the search online button every time 👍

**Comment by vdesabou** [comment]
Hi, 

Thanks for the suggestion but I don't really like the idea...The goal of the workflow is to be very quick to display results in our own library. Looking up results online is very slow because I need to interrogate spotify API.. So doing by default a search online would make the workflow very slow.


However, have you noticed that when you do a search, overtime at the end of results, you have an option to look up online, see:

![screen shot 2016-05-16 a 12 03 57](https://cloud.githubusercontent.com/assets/4061923/15286670/9f844fa8-1b5e-11e6-9f37-217956784615.jpg)

So you can type your search and select to do an online search if it is not in your library..

**Comment by dcaixinha** [comment]
Hmm, I see. But since it was an option, people would only get slower results if they chose to! But I get the point 👍

**Comment by vdesabou** [comment]
Closing, I really prefer to stay with search online fallback at the end of the results, but thanks for the suggestion !
