### ISSUE TITLE
It stucks progress sync

### ISSUE THREAD

**Issue by ttuygun** [vdesabou/alfred-spotify-mini-player#128]
It stucks in progress sync "Creating library for since 5 hr...". Even if remove the workflow from Alfred menu or reset the workflow from alfred-spotify-mini-player settings, nothing has changed. API keys will remembered and I can't reauthenticate and restart the setup process. Where is my API credentials stored?

**Comment by vdesabou** [comment]
Please follow steps from here 
http://alfred-spotify-mini-player.com/articles/support/

I need the TGZ file to investigate 

Vincent

**Comment by ttuygun** [comment]
I sent an email.

**Comment by vdesabou** [comment]
Thanks for the TGZ file

To stop the update: type "spot_mini_kill"
To reset the workflow: type "spot_mini_reset_settings"

After that, you should be in the case where the workflow asks for your credentials, (then follow http://alfred-spotify-mini-player.com/setup/)

If for some reasons the spot_mini_reset_settings does not work. Then type "spot_mini_debug " and choose Browse to App Support folder, this is where settings.json file is stored. Remove the file manually.

If that ever happen, please send another TGZ file because normally spot_mini_reset_settings should work

Keep me updated

**Comment by ttuygun** [comment]
After deleting all contents in workflow's App Support folder, it works again. Thanks.

**Comment by vdesabou** [comment]
good !
