### ISSUE TITLE
Featured playlist that are followed

### ISSUE THREAD

**Issue by fenrisbear** [vdesabou/alfred-spotify-mini-player#142]
I noticed that featured playlists your subscribed to are not searchable.
Given that Spotify now more frequently adds playlists especially tailored your music habits, I think it is essential to add this at some point down the line.

There's a "featured playlists", but this one is for searching through the currently available playlists provided by Spotify? It makes sense that these playlists end up in your playlist search whenever you follow them.

An example of such a playlist is "Release Radar". This one in particular popped up in the news just a few weeks ago.

**Comment by vdesabou** [comment]
Not sure to understand the problem here, I think you just need to _follow_ the playlist you want, and then it is added in your playlists and then you can search for it as any other of your playlists. 

For example, you find a playlist in the featured playlists, then you choose to follow it:

![screen shot 2016-08-16 a 10 04 33](https://cloud.githubusercontent.com/assets/4061923/17692187/de2b8b7c-6398-11e6-851b-14981a7769f8.jpg)

Then the workflow will automatically add it in your Library and then the playlist is searchable as any other.

It's same for Release Radar playlist

![screen shot 2016-08-16 a 10 06 05](https://cloud.githubusercontent.com/assets/4061923/17692233/125886f2-6399-11e6-9e6e-3def23333daa.jpg)

**Comment by vdesabou** [comment]
Closing as no feedback, re-open if needed
