### ISSUE TITLE
quick play Daily Mix

### ISSUE THREAD

**Issue by camscofie** [vdesabou/alfred-spotify-mini-player#202]
Would it be awesome, if we can just play Daily Mix like play a Playlist?

Thanks for you time.
👍

**Comment by vdesabou** [comment]
That’s impossible unfortunately, see https://github.com/vdesabou/alfred-spotify-mini-player/issues/166

**Comment by SpotifyThrowaway** [comment]
This is in fact possible, and not too difficult to implement.  It uses undocumented Spotify APIs which is why I'm commenting using a throwaway account to stay on their good side.

First, you'll need to add two settings to allow a user to specify their Spotify username and password.  It's then possible to exchange those for an access token:

1. Request the log in page:
https://accounts.spotify.com/login?utm_source=open&utm_medium=signup-test&utm_campaign=navigate&continue=https%3A%2F%2Fopen.spotify.com%2Fbrowse

The log in page provides a CSRF token (via csrf_token cookie) which will be needed in future requests.

2. Make a POST request to the Spotify login API endpoint:
https://accounts.spotify.com/api/login

The API requires three fields: remember=true&username={user}&password={pw}&csrf_token={token}

The csrf_token field should be populated with the token retrieved in step 1.  Two new cookies should be added to the request:

remember: Set this to the username of the account being logged into.
__bon: This is a base64 encoded set of 8 integers separated by a pipe (no idea what it's for).  You can seemingly generate a valid one by base64 encoding the string "0|0|0|0|1|1|1|1".

Assuming the login is successful, three new cookies will be set: sp_ac, sp_dc and a new csrf_token.

3. Send these new cookies to a URL on the open.spotify.com domain, for example:
https://open.spotify.com/browse

The response will include four new cookies: wp_sso_token, wp_access_token, wp_expiration and wp_expires_in.  The access token which can be used to access Spotify APIs is held in the wp_access_token cookie.

4. When the token expires, you don't need to go through the whole process again.  You can refresh it by sending a GET request to:
https://open.spotify.com/refresh_token

Include the cookies from step 3.  The JSON response will contain a new access token and new cookies will be set.

Now you have a valid access token which can be used to fetch a user's Daily Mixes, but can also be used to interact with the official, public Web API as well.  Just use standard bearer authentication.

Get a list of Daily Mixes:

    GET https://spclient.wg.spotify.com/radio-apollo/v3/clusters?salt=7&image_style=gradient_overlay&market=from_token

Get the tracks of a specific Daily Mix:

    GET https://spclient.wg.spotify.com/radio-apollo/v3/stations/{station_uri}?salt=7&count={count}&image_style=gradient_overlay&market=from_token

There are similar API endpoints for liking/disliking a song from a station.  I'll leave you to explore those yourself ;)

Hope that helps!

**Comment by vdesabou** [comment]
@SpotifyThrowaway Thanks for this impressive guide ! I'm not 100% sure I'll use it in a next version of the workflow as I'm not really keen to use private APIs like this. But I'll keep in mind if Spotify takes too much time to include this in public API.

Thanks again for your post
