### ISSUE TITLE
Create Song and Artist radio without creating playlists?

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#219]
In Spotify client when you make Song or Artist radio of a song, it will create the radio but not create the playlist.

I really like this as very often I actually delete these annoying Song and Artist radio playlists that the workflow creates. If other users do like it though, perhaps we can make it an option for the playlists to be created or not. I hope this doesn't add too much complexity to an already awesome workflow.

**Comment by vdesabou** [comment]
Technically, I need to create a playlist because that's the only thing we can play. However, I've made a change in order to delete the playlist once it has been launched.
I'll not make it configurable, it does not really make sense to keep the radios in library.

Can you try this beta https://transfer.sh/TVpk/spotifyminiplayer-beta.alfredworkflow

**Comment by nikitavoloboev** [comment]
This works superbly. Thank you.
