### ISSUE TITLE
Is it possible to search and play local files through workflow?

### ISSUE THREAD

**Issue by nikitavoloboev** [vdesabou/alfred-spotify-mini-player#222]
I have an external folder that I made and attached to Spotify like so: 

![2018-01-06 at 21 02](https://user-images.githubusercontent.com/6391776/34643467-f9d00a0c-f324-11e7-8dfc-618dfab296d8.png)

This folder contains mp3's I loaded locally so I can play them with Spotify:

![2018-01-06 at 21 03](https://user-images.githubusercontent.com/6391776/34643475-14f181a8-f325-11e7-8955-76f48d21bd4c.png)

Is it possible for the workflow to search and play these files in some way?

**Comment by nikitavoloboev** [comment]
Actually never mind. iTunes is a better app for local playing anyway. 🙂

**Comment by vdesabou** [comment]
To answer your question, yes it is possible to do that with the workflow, however the workflow is really working as best effort because Spotify API support of local tracks is really bad. Example: Applescript is no more working to play local tracks https://github.com/vdesabou/alfred-spotify-mini-player/issues/82

Same thing for Spotify Web API, local tracks are badly supported.
Mopidy also not support local tracks, see known issues list [here](http://alfred-spotify-mini-player.com/known-issues/)

Overall, using local tracks with the workflow is not really recommended as user experience might not be good. There's not much I can do since this is issues with Spotify that are ignored by them
