### ISSUE TITLE
Song notification artwork

### ISSUE THREAD

**Issue by Noskcaj19** [vdesabou/alfred-spotify-mini-player#224]
Would it be possible to support artwork in the "App Icon" of the song notification like iTunes does?  terminal-notifier seems to support this through the `-appIcon` flag

**Comment by vdesabou** [comment]
Well, I think it does already, see example in

> http://alfred-spotify-mini-player.com/articles/now-playing/

Don’t you have the artwork on the right hand side?
Sorry I don’t use iTunes, so I don’t know how it looks like.
Can you show an example?
-- 
Vincent de Saboulin

**Comment by Noskcaj19** [comment]
Yes, currently the artwork is displayed in the right side of the notification, along with an icon of the Terminal, which is a bit distracting.

iTunes seems to use a private api to set the left side icon, like this:
<img width="385" alt="itunes" src="https://user-images.githubusercontent.com/9626718/34906532-66a4d76c-f83d-11e7-8ebb-1f47a5af900f.png">

**Comment by vdesabou** [comment]
So I've updated terminal-notifier and now using appIcon, so instead of:

![screenshot 2018-01-16 at 12 01 38](https://user-images.githubusercontent.com/4061923/34985889-e8c2fcc2-fab5-11e7-9611-b397d4b0e659.jpg)


I get:

![screenshot 2018-01-16 at 12 01 16](https://user-images.githubusercontent.com/4061923/34985901-ed6dfbd2-fab5-11e7-85a1-c706b94a6aef.jpg)

Even though the artwork is smaller, it looks better, so I'll go ahead with modification.

However, you should not see terminal icon in your notifications. You should see Spotify Mini Player icon like I do, see screenshot above.

Can you do this:

![screenshot 2018-01-16 at 12 11 11](https://user-images.githubusercontent.com/4061923/34986033-6179eaf4-fab6-11e7-94fc-e5e900e5a036.jpg)

Then choose Browse to Alfred Workflow folder.

And then double click on Spotify Mini Player.app:

![screenshot 2018-01-16 at 12 12 15](https://user-images.githubusercontent.com/4061923/34986082-81af56a6-fab6-11e7-8a4e-3c9e02130d48.jpg)


If you use another theme (not the green one), I think there is a bug where apps are not present, I've fixed it in next release
