### ISSUE TITLE
Previous track command does not go to previous track

### ISSUE THREAD

**Issue by koyedele** [vdesabou/alfred-spotify-mini-player#270]
Really love the product! Big kudos to you for putting this out for us!

My issue is when I type "previous track", it doesn't really go to the previous track but to the beginning of the current song. "Next track" works correctly, by the way. I experience this on the Mac as well when I use the media control keys to skip between tracks. I have to hit the "<<" button twice to get the previous track to play and in the same way, the ">>" button works correctly. This makes me wonder if it is a problem with Spotify itself. When using Alfred, however, I can't type "previous track" fast enough! 😄 
Is this something you can fix?

**Comment by vdesabou** [comment]
That's correct, it seems to be an issue with Spotify Applescript. As a workaround, I'm calling it twice now, so first time it goes to beginning of track and then second time it goes to previous track. 

You can test the beta here https://transfer.sh/LTReG/spotifyminiplayer-beta.alfredworkflow


Note: This issue only happens when using Spotify Desktop, it does not happen when using [Spotify Connect](http://alfred-spotify-mini-player.com/articles/spotify-connect/), so if you're a premium subscriber, I recommend to use Spotify Connect.

**Comment by koyedele** [comment]
Great! I switched to Spotify Connect and it works as expected with v7.17! Also tested the beta build and verified that both using Spotify Connect and Spotify Desktop work as expected. Thanks so much!

**Comment by vdesabou** [comment]
Cool ! Yes Spotify Connect is definitely better. In fact, I want to get rid of "Spotify Desktop" (Deprecate use of Spotify Desktop Applescript #253) option because it is using AppleScript which is buggy as hell.
Once Spotify allows non-premium users to use Spotify Connect, I'll only use Spotify Connect
