### ISSUE TITLE
Spotify Mini Player Update

### ISSUE THREAD

**Issue by daniel-joseph** [vdesabou/alfred-spotify-mini-player#334]
Hello there, 
When I updated to version 8.5, it created a new workflow in alfred. So I had one workflow for 8.4 and one for 8.5. However, the one with version 8.5 did not have any of my key bindings. Do I need to delete the one with version 8.4, and reconfigure my keyboard shortcuts on the new workflow with version 8.5? I hope this isn't a stupid question. I'm just hesitant to delete my version 8.4, and have to rebuild the mini player from scratch.

Thank you so much!
Daniel Gonzalez

**Comment by vdesabou** [comment]
Hi Daniel,

There is no reason it would create another workflow because the bundle id has not changed `com.vdesabou.spotify.mini.player`.

Normally, if you double click on the workflow, you should see a window like this: 

![Screenshot 2020-04-06 at 11 45 27](https://user-images.githubusercontent.com/4061923/78545564-44ebf600-77fc-11ea-9bdb-39214b149582.png)

**Comment by daniel-joseph** [comment]
I looked at the bundle id of the original workflow with version 8.4, and it was 
`com.vdesabou.spotify.mini.player1`

I am not sure why this is, but the updated workflow that was created with version 8.5 had bundle id
`com.vdesabou.spotify.mini.player`

Only the bundle id with number 1 appended at the end would update my library and function, so i just changed the bundle id on the new one and deleted the prior.
Thanks
