### ISSUE TITLE
Error "Fill missing information in spotify and retry again"

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/alfred-spotify-mini-player#349]
Applescript support with Spotify is getting really bad

For almost every track, it does not return artist and album names anymore:

```
➜ ./track_info.ksh 
▹▹Every Kingdom▹playing▹spotify:track:4ZudIxIgp0fOgy0C1EcrQC▹397211▹0
```

**Comment by aCluelessDanny** [comment]
Just gonna chime [this](https://community.spotify.com/t5/Desktop-Mac/Applescript-no-longer-reports-Spotify-Connect-song-playing/m-p/4925257) in here on this since a number of people are dealing with this in other tools.

Gist of it is the song name and artist name are returned as blank under certain circumstances (such as pausing or skipping tracks). There's not much else to do until it gets fixed other than reverting to an older Spotify version or using the web API
