### ISSUE TITLE
Missing Playlists

### ISSUE THREAD

**Issue by cmds4410** [vdesabou/alfred-spotify-mini-player#37]
It's very possible this is a known issue or I'm doing something wrong on my end. When I updated the library it removed many of my playlists and I have not been able to restore them with subsequent upgrades. I'll probably need to reset the whole library.

**Comment by vdesabou** [comment]
I assume you're talking about when upgrading from 4.x to 5.x version, right. In 5.x, the API used is different (Web API rather than Spotify App API).
Are these missing playlists "collaborative playlists"? If so, yes this is a known issue in the Spotify Web API, see list of known issues for workflow here https://github.com/vdesabou/alfred-spotify-mini-player/wiki/Known-Issues. Also the Starred playlist is not retrieved as well.

If the missing playlists are not collaborative, then please provide the TGZ file generated by using command `spot_mini_debug`. You can send it to the email in my GitHub profile.

**Comment by cmds4410** [comment]
5.2 was the first version I downloaded, I mean when I called the "spot_mini_update_library."
Will send the debug files now. Thanks!

**Comment by vdesabou** [comment]
Thanks for the debug file. You're hitting this bug https://github.com/vdesabou/alfred-spotify-mini-player/issues/35 in 5.2 version, which is fixed in the next coming release 6.0

Using version 6.0, I have no problem using your library:

![screenshot](https://cloud.githubusercontent.com/assets/4061923/5736136/61b02628-9bd2-11e4-9c12-0fa5068a9445.png)

And I see your 147 playlists:

![screenshot2](https://cloud.githubusercontent.com/assets/4061923/5736145/86ba179e-9bd2-11e4-93a3-f8e4dcfa10b6.png)

I'm going to send you by email a beta version of 6.0 so that you can test on your side as well.

**Comment by vdesabou** [comment]
Did you try version 6.0 ? I'm always interested in feedback :smile:

**Comment by twayz** [comment]
hey. i've been having the same issue. I'd love to try out the beta! keep up the great work!

**Comment by vdesabou** [comment]
> hey. i've been having the same issue. I'd love to try out the beta! keep up the great work!

Sure, here is the link http://cl.ly/1o3O0p3R1t1m
However, this version is built on a beta version of Alfred, so I'm not 100% it will work with your version. 
Let me know if this works or not !

**Comment by twayz** [comment]
thanks! and your right it says its incompatible with my version of Alfred. is the beta version public? thanks!

**Comment by vdesabou** [comment]
Ok, I was not sure. Thanks for confirming.
No it is not a public beta..It is beta with Alfred remote support. Alfred team hopes to release it within the next couple of weeks. Once Alfred remote it out, I'll release version 6.0. You will have to wait a bit I'm afraid..

Cheers

Vincent

**Comment by cmds4410** [comment]
Sorry for the delay @vdesabou! I just installed the beta and got the same message of incompatibility. Thanks for sending though, I'm glad it will be fixed in the next update!

**Comment by vdesabou** [comment]
Version 6.0 is now live. It will fix this issue. Get it here http://alfred-spotify-mini-player.com

**Comment by cmds4410** [comment]
Awesome, updating now.
