### ISSUE TITLE
Feature Request: Send Commands to Spotify Daemon (Mopidy)

### ISSUE THREAD

**Issue by twayz** [vdesabou/alfred-spotify-mini-player#40]
Hi,

I was wondering if you plan to integrate the ability to send commands to Spotify using a daemon instead of the Spotify.app? I attached two links to two Spotify Daemons I found on Github. However, using the daemon requires a premium account. Awesome extension!

Thanks
https://github.com/SimonPersson/spotifyd
https://github.com/Schnouki/spop

**Comment by vdesabou** [comment]
Hi,

>I was wondering if you plan to integrate the ability to send commands to Spotify using a daemon instead of the Spotify.app? 

I am no more using a Spotify App since version 5.x. I'm now using official [WEB API](https://developer.spotify.com/web-api/). So I got off the "hacky" way, by using the official and evolving Spotify API, so I'm not really keen going back to using some kind of mysterious hack again :smile: 

>I attached two links to two Spotify Daemons I found on Github. However, using the daemon requires a premium account.

Thanks, I was not aware of these projects. However, I do not see what would be the added value compared to current version 6.0. Do you have some new features in mind that you can list?
Of course the main drawback is that it would require a Premium account

> Awesome extension!

Thanks, I appreciate this. I hope you've downloaded version 6.0 and have a look at the brand new site http://alfred-spotify-mini-player.com/ !

**Comment by twayz** [comment]
Thanks for responding. I guess the added value would simply be not having to launch the Spotify GUI, which is pretty resource intense. Also, your extension pretty much replaces the Spotify app for me after all the added features. It almost functions as a Spotify client. The Spotify daemon would always be running in the background and ready in an instance only utilizing few resources. -- Just a thought. Thanks!

**Comment by vdesabou** [comment]
I'll stick with Spotify WEB API as I don't want to restrict the workflow to Spotify Premium subscribers only.
Closing for now, but thanks for sharing these two projects!

**Comment by vdesabou** [comment]
Another related projects:-

* mopidy-spotify

* spotifyd

**Comment by MartinAyla** [comment]
Well, I would just like to +1 this.

It would be nice not having to run the (resource heavy) GUI app in the background.

I tried mopidy-spotify + ncmpcpp (with brew). It's nice, but I would rather control it through Alfred instead of a console GUI.

**Comment by vdesabou** [comment]
>I tried mopidy-spotify + ncmpcpp (with brew). It's nice, but I would rather control it through Alfred instead of a console GUI.

FYI, I changed my mind due to the [very poor update 1.x](http://alfred-spotify-mini-player.com/blog/issue-with-latest-spotify-update/) from Spotify and I decided to start implementing support of [mopidy-spotify](https://github.com/mopidy/mopidy-spotify) :smile: 

No ETA yet, but if you would like to be a beta tester, that would be great!

**Comment by vdesabou** [comment]
implemented as part of https://github.com/vdesabou/alfred-spotify-mini-player/commit/50e3253ae3bf289a98177c0e507188e112fad593

**Comment by vdesabou** [comment]
This is available in Version 6.2
See article http://alfred-spotify-mini-player.com/articles/mopidy/
