### ISSUE TITLE
Check if Alfred version is compatible prior to update

### ISSUE THREAD

**Issue by t89** [vdesabou/alfred-spotify-mini-player#410]
The workflow notified me, that an update was available. I installed it and now I cannot use the workflow anymore, because I have an outdated Alfred version.

Issues:
- Update script should check compatibility before notifying the user of an update
- Before the update is installed, the user should be notified about incompatibilities
- Is there a way of downgrading the workflow **without losing all settings**?

**Comment by vdesabou** [comment]
Thanks for the suggestions. I'll implement that for future Alfred 5 release. But for previous releases, it is too late now unfortunately. This is the first someone reports me this issue, I guess everybody has upgraded Alfred version

- If you use Alfred 2, you can download latest compatible version [here](https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/v6.2.6)
- If you use Alfred 3, you can download latest compatible version [here](https://github.com/vdesabou/alfred-spotify-mini-player/releases/tag/v-8.5)

I don't think you should loose settings, but I can't test because I don't have those Alfred versions installed.
You can disable auto-update by removing `checkForUpdate`in main.php file

**Comment by t89** [comment]
Thank you
