### ISSUE TITLE
Is the library creation necessary?

### ISSUE THREAD

**Issue by Jendker** [vdesabou/alfred-spotify-mini-player#421]
Thank you for the great workflow!
I would have one question to which I could not find the introduction in the setup.

Is it actually actually necessary to Create a library? What is the actualy function of it? 

Could you please tell mewhere does he put all the files? I like to have the control over what I have on my Mac. Right now he is downloading 15000 thumbnails, because I have saved many playlists. It took a while to get to 500 so I killed the process.

**Comment by vdesabou** [comment]
Yes it is mandatory, it is actually the main power of this workflow, since it builds a local version of your library so that you can access all your music instantaneously.
But don't worry, this is a local (sqlite) copy on your computer. You can access the database using Browse to App Support folder when you type `spot_mini_debug `:

![Screenshot 2020-11-11 at 09 38 51](https://user-images.githubusercontent.com/4061923/98788893-c98d9b00-2401-11eb-8a8c-7c1454a48022.png)

The file is called `library.db`
Again, it is a local copy only, it is not uploaded anywhere

Regarding the thumbnails, yes it download everything in the background, so that you can see nice artworks in the search results. There are stored also locally in App Support folder under `artwork`
If you really don't want to use artworks, you can disable it in settings:

![Screenshot 2020-11-11 at 09 43 08](https://user-images.githubusercontent.com/4061923/98789293-651f0b80-2402-11eb-9a14-1e02b5f9ea62.png)

Let me know if you have any questions

**Comment by Jendker** [comment]
I think that was it, thank you very much for the complete answer! If there will be anything more I will open a new issue or try open PR.

Cheers!
