### ISSUE TITLE
FR: Option to follow the currently playing playlist

### ISSUE THREAD

**Issue by chrisgrieser** [vdesabou/alfred-spotify-mini-player#526]
with the "Current Track" Submenu, I can pretty much do everything but follow the currently playing playlist to my music ("follow" the playlist, not the Alfred Playlist). The only way to follow a playlist that I could find was to browse to it via "Browse", and then select "follow privately".

Is there a way to simply add the currently playing playlist to my music that I have overlooked? If not, then I'd submit the feature request of having a quick option somewhere to add the currently playing playlist to my music.

<img width=50% alt="Screenshot 2021-10-04 02 12 14" src="https://user-images.githubusercontent.com/73286100/135778365-a2d9009c-a921-45fb-9cc4-22fa15bbe85f.png">

**Comment by vdesabou** [comment]
@chrisgrieser I had a quick look and it should be possible to add a modifier key in order to follow the playlist.
That will be available only when Spotify Connect is used (we don't have the playlist when AppleScript is used)
I'll include this feature in a future version.

Note to myself, code is here https://github.com/vdesabou/alfred-spotify-mini-player/blob/5196c9f3ab1c0820ca3dda4446a7c5f3af11d8d4/spotify-mini-player/src/firstDelimiter.php#L1082

**Comment by chrisgrieser** [comment]
thanks! :)

**Comment by vdesabou** [comment]
Added in 11.7

![CleanShot 2021-11-15 at 15 26 02](https://user-images.githubusercontent.com/4061923/141798737-12c81a28-0bdc-4c3c-8963-6a3269d35fc5.jpg)

**Comment by chrisgrieser** [comment]
fantastic, thanks a lot <3

**Comment by vdesabou** [comment]
Leaving it opened until 11.7 is released
