### ISSUE TITLE
Automatically play next track when removing track from any playlist or your music

### ISSUE THREAD

**Issue by vdesabou** [vdesabou/alfred-spotify-mini-player#535]
Improvement from #522 to apply to any playlist

**Comment by amarukot** [comment]
transferring my comment from #522 to here.

this new feature is great because I've thought about this before. But I'm hoping to make it optional or at least as a separate action? Sometimes you just want to remove from playlist but DO want to keep listening.

remove_current_track_from_and_play_next
remove_current_track_from

e.g. I'm listening to a "new songs" playlist and I hear a song that I want to move to a different playlist. I want to remove from "new songs" playlist but want to keep listening. Is this possible?
