### ISSUE TITLE
Bug: Icon broken since Update to macOS monterey

### ISSUE THREAD

**Issue by chrisgrieser** [vdesabou/alfred-spotify-mini-player#553]
Since updating to Monterey, the icon seems to be broken. Out of all Alfred workflows, only this one seems be to be affected by it.  I have installed php as instructed in the known issues and everything else seems to work fine.

<img width="137" alt="Screenshot 2021-12-06 10 29 10" src="https://user-images.githubusercontent.com/73286100/144821896-6bde23be-a0f8-48be-903f-f6c8e4db7d41.png">

**Comment by vdesabou** [comment]
Seems like a permission issue.

Since version 11.15 and https://github.com/vdesabou/alfred-spotify-mini-player/issues/540, the permissions are fixed automatically. Which version are you using ?

You can try to execute manually:

![CleanShot 2021-12-06 at 12 31 51](https://user-images.githubusercontent.com/4061923/144838847-9904ab50-41cc-4025-b565-334df1b7b5a8.jpg)


And then reboot your Mac (it is generally required)

**Comment by chrisgrieser** [comment]
fixing permissions and restarting solved it. Thanks also for the quick response!
